# This is a basic workflow to help you get started with Actions

name: Update Badge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    runs-on : ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Generate SVG
        run: |
          python .github/workflows/generate_badge.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@gihub.com"
          git add badge.svg
          git add counter.txt
          git commit -m "Update badge"
          git push
